### ISSUE TITLE
[BUG] prplMesh is not operational on Raspberry Pi 3 B+

### ISSUE THREAD

**Issue by MuteSpirit** [prplfoundation/meta-prplmesh#12]
## Steps for reproduce

* Boot board
* /opt/prplmesh/scripta/prplmesh_utils.sh start
* /opt/prplmesh/scripta/prplmesh_utils.sh status

## Actual behavior

* prplMesh processes run on board
* but prplmesh is *not operational*

## Logs and conf files

* Boot log: [rpi3bplus-rdkb-next-boot.log](https://github.com/prplfoundation/meta-prplmesh/files/4682726/rpi3bplus-rdkb-next-boot.log)
* Network ifaces presented on RPi: [rpi3bplus-rdkb-next-prplmesh-ifaces.log](https://github.com/prplfoundation/meta-prplmesh/files/4682728/rpi3bplus-rdkb-next-prplmesh-ifaces.log)
* prplMesh start log: [rpi3bplus-rdkb-next-prplmesh-start.log](https://github.com/prplfoundation/meta-prplmesh/files/4682723/rpi3bplus-rdkb-next-prplmesh-start.log)
* prplMesh components logs:
  * [beerocks_controller.log](https://github.com/prplfoundation/meta-prplmesh/files/4682725/beerocks_controller.log)
  * [local_bus.log](https://github.com/prplfoundation/meta-prplmesh/files/4682724/local_bus.log)
  * [transport.log](https://github.com/prplfoundation/meta-prplmesh/files/4682727/transport.log)
  * [beerocks_agent_wlan0.log](https://github.com/prplfoundation/meta-prplmesh/files/4682729/beerocks_agent_wlan0.log)
  * [beerocks_agent_wlan1.log](https://github.com/prplfoundation/meta-prplmesh/files/4682730/beerocks_agent_wlan1.log)
* prplMesh config files (extensions changed `.conf` -> `.conf.txt` to bypass GitHub restrictions)
  * [beerocks_controller.conf.txt](https://github.com/prplfoundation/meta-prplmesh/files/4682775/beerocks_controller.conf.txt)
  * [beerocks_agent.conf.txt](https://github.com/prplfoundation/meta-prplmesh/files/4682777/beerocks_agent.conf.txt)

## Version

* Board: 
  * Raspberry Pi 3 B+ 
  * Attached Wi-Fi USB dongle
  * Two wlan ifaces: wlan0 and wlan1
* [HOWTO build image manual](https://github.com/prplfoundation/meta-prplmesh/issues/9#issuecomment-632005427)
> but use branch "n9-support-bwl-type-nl80211" for "meta-prplmesh" repo

**Comment by MuteSpirit** [comment]
Comment from @arnout :
```
wpa_ctrl_open() failed, ctrl_iface_path: /var/run/hostapd/wlan0 -> on RPi/RDK-B, the hostapd control socket is in a different place.
You have to find where it is and adapt the code accordingly.
Probably the path should come from bpl.
```

As i see on RPi the hostapd unix sockets paths is more complex then bwl expected:
```
unix  2      [ ]         DGRAM                     26702 /var/run/hostapd4/wlan0
unix  2      [ ]         DGRAM                     23381 /var/run/hostapd0/wlan1
```

**Comment by MuteSpirit** [comment]
> Comment from @arnout :
> 
> ```
> wpa_ctrl_open() failed, ctrl_iface_path: /var/run/hostapd/wlan0 -> on RPi/RDK-B, the hostapd control socket is in a different place.
> You have to find where it is and adapt the code accordingly.
> Probably the path should come from bpl.
> ```

I've changed pathes to unix sockets in hostapd conf files on board and controller and 1st agent became operational
```
/opt/prplmesh/scripts/prplmesh_utils.sh: status                              
14141 /opt/prplmesh/bin/beerocks_monitor                                                   
14177 /opt/prplmesh/bin/beerocks_monitor                                                  
29486 /opt/prplmesh/bin/beerocks_controller                                                
29487 /opt/prplmesh/bin/beerocks_agent                                                    
29618 /opt/prplmesh/bin/beerocks_agent                                                    
29629 /opt/prplmesh/bin/beerocks_agent                                                     
29483 /opt/prplmesh/bin/ieee1905_transport                                                
29482 /opt/prplmesh/bin/local_bus                                                          
OK Main agent operational                                             
OK wlan0 radio agent operational                                             
FAIL wlan2 radio agent operational
```

Right now the path to hostapd/wpa_supplicant is hard-coded in prplmesh agent.
https://github.com/prplfoundation/prplMesh/blob/14027e845ac3bf60a1099d9bae0f17b0b4b4bea3/common/beerocks/bwl/nl80211/base_wlan_hal_nl80211.cpp#L221

I think it's better to have option in config file for that paths

**Comment by MuteSpirit** [comment]
I've suggested [prplMesh PR #1363](https://github.com/prplfoundation/prplMesh/pull/1363) with fix.
Using that code i see **operational** controller and both agents

**Comment by aswath2481** [comment]
Hi people, I have followed the steps to build RDK-B image with prplmesh. I connected Rpi with PC via ethernet port. I have the following logs printed on UART port during the boot up. It seems both the ethernet and wifi systems are down as i am not able to find SSID of the RPI and the ip scanning on ethernet port shows no active lighthttpd.  Can anyone help me to debug the issue?
Thanks for our support.
[RPI_log_RDKB_prpl_17_06_20.txt](https://github.com/prplfoundation/meta-prplmesh/files/4824112/RPI_log_RDKB_prpl_17_06_20.txt)

**Comment by MuteSpirit** [comment]
Hi @aswath2481,

1. There is next line in your bool log

```
[    5.645742] RTL871X: hal_com_config_channel_plan chplan:0x21
```

Possibly it's [Wireless Country Code Issue](https://openwrt.org/toh/raspberry_pi_foundation/raspberry_pi)

```
The Country Code under Wireless in OpenWrt does not work, and you do need to set/change the country code in the latest Raspbian, and then you can go back to OpenWrt; the new country code will be used. Starting with Raspberry Pi 3 B+, the on-board wireless won't even start if there is no country code (set in Raspbian) See: https://forum.openwrt.org/t/cannot-use-channels-12-and-13-on-raspberry-pi-3-in-ap-config/3707/3
```

2. RDK-B WiFi client is present in image

There are messages from CcspWifiSsp
```
[   41.275943] CcspWifiSsp[2254]: device wlan1 is already a member of a bridge; can't enslave it to bridge brlan0.
[   41.531817] CcspWifiSsp[2254]: wlan2     No such device
[   41.554683] CcspWifiSsp[2254]: Conf file /etc/debug.ini open success
[   41.555811] CcspWifiSsp[2254]: rdk_logger_init /etc/debug.ini Already Stack Level Logging processed... not processing again.
[   41.556690] CcspWifiSsp[2254]: 				 ********ENTER breakpad_ExceptionHandler******************
[   41.557501] CcspWifiSsp[2254]: 				 ******** breakpad_ExceptionHandler EXIT******************
```

But CcspWifiSsp uses nl80211 and will conflict with prplMesh and should be absent in image or killed manually after board boot.

Please check that you use branch [n9-support-bwl-type-nl80211](https://github.com/prplfoundation/meta-prplmesh/tree/n9-support-bwl-type-nl80211) where present commit [a1dbc51e3aeca1d8dca5dc4865d79c9e26516d0c](https://github.com/prplfoundation/meta-prplmesh/pull/11/commits/a1dbc51e3aeca1d8dca5dc4865d79c9e26516d0c)

**Comment by aswath2481** [comment]
Hi @MuteSpirit , thanks for helping us with the issue. I log file I attached is generated from the image created using the above mentioned branch and the commit is also done already. But I noticed that the logs you mentioned aren't from the logs which I attached. Can you recheck again. Thanks.

**Comment by MuteSpirit** [comment]
Hi @aswath2481,

I'm busy on another project and cannot accurately recheck build on current state of "rdk-next" branch.

As i remember - on my RPi the CCSP Wi-Fi agent also could not up Wi-Fi ifaces and tried again and again and spammed the serial console with it's messages.

Try next:
* add into "conf/local.conf"
```
IMAGE_INSTALL_remove = "ccsp-wifi-agent"
``` 
and rebuild image
* **OR** kill `CcspWifiSsp` process after board boot and run prplMesh
```
/opt/prplmesh/scripts/prplmesh_utils.sh start
```

Best regards

**Comment by MuteSpirit** [comment]
Possible reason has been detected.

After removing `ccsp-wifi-agent` from image the hostapd processes does not start on board boot
So to become prplMesh operational it's needed to run manually
```
hostapd -B /usr/ccsp/wifi/hostapd0.conf
/opt/prplmesh/scripts/prplmesh_utils.sh restart
```
